<?php
define('__ROOT__', dirname(dirname(__FILE__)));

if($_POST['action']=='install'){
	
	if(file_exists(__ROOT__.'/inc/config.php') == TRUE){
		echo '<div class="alert alert-info alert-dismissible"><strong>System is already configured!</strong></div>';
		return;
	}

	if(strlen($_POST['password']) < '5'){
		echo '<div class="alert alert-danger alert-dismissible"><strong>Error: </strong>Password must be at least 5 characters long!</div>';
		return;
	}
	
	if(!$_POST['dbhost'] || !$_POST['dbuser'] || !$_POST['dbpass'] || !$_POST['dbname'] || !$_POST['username'] || !$_POST['fullName'] || !$_POST['email']){
		echo '<div class="alert alert-danger alert-dismissible"><strong>Error: </strong>All fields are required.</div>';
		return;
	}
	
	if ( ! is_writable(dirname(__FILE__))) {
		echo '<div class="alert alert-danger alert-dismissible"><strong>Error: </strong>Home directory isn\'t writable.<p>Please refer to our <a href="https://www.jbparfum.com/knowledge-base/" target="_blank">KB</a> for help.</p></div>';
		return;
	}
	
	if(!$link = mysqli_connect($_POST['dbhost'], $_POST['dbuser'], $_POST['dbpass'], $_POST['dbname'])){
		echo '<div class="alert alert-danger alert-dismissible">Error connecting to the database, make sure the details provided are correct, the database exists and the user has full permissions on it.</div>';
		return;
	}

	
	$cmd = 'mysql -u'.$_POST['dbuser'].' -p'.$_POST['dbpass'].' -h'.$_POST['dbhost'].' '.$_POST['dbname'].' < ../db/pvault.sql'; 
	passthru($cmd,$e);
	if(!$e){
		mysqli_query($link,"INSERT INTO users (email,password,fullName) VALUES ('".strtolower($_POST['email'])."',PASSWORD('".$_POST['password']."'),'".$_POST['fullName']."')");
		
		$conf = '<?php
//AUTO GENERATED BY INSTALLATION WIZARD
if (!defined("pvault_panel")){ die("Not Found");}
$dbhost = "'.$_POST['dbhost'].'"; //MySQL Hostname
$dbuser = "'.$_POST['dbuser'].'"; //MySQL Username
$dbpass = "'.$_POST['dbpass'].'"; //MySQL Password
$dbname = "'.$_POST['dbname'].'"; //MySQL DB name


$uploads_path = "uploads/";
$tmp_path = "tmp/";
$allowed_ext = "pdf, doc, docx, xls, csv, xlsx, png, jpg, jpeg, gif";
$max_filesize = "4194304"; //in bytes
?>
';
	}else{
		echo '<div class="alert alert-danger alert-dismissible">Error: '.mysqli_error($link).'</div>';
		return;
	}
	
	
	if(file_exists('/config/.DOCKER') == TRUE){
		$cfg = '/config/config.php';	
	}else{
		$cfg = __ROOT__.'/inc/config.php';
	}

	if(file_put_contents($cfg, $conf) == FALSE){
		echo '<div class="alert alert-danger alert-dismissible">Error: failed to create config file <strong>'.$cfg.'</strong><p> Make sure your web server has write permissions to the install directory.</p></div>';
		return;
	}
	
	$app_ver = trim(file_get_contents(__ROOT__.'/VERSION.md'));
	$db_ver  = trim(file_get_contents(__ROOT__.'/db/schema.ver'));
	mysqli_query($link,"INSERT INTO pv_meta (schema_ver,app_ver) VALUES ('$db_ver','$app_ver')");
		
	echo '<div class="alert alert-success alert-dismissible">Success: System configured!</div>';
	return;
}
?>
