<?php
//AUTO GENERATED BY INSTALLATION WIZARD
if (!defined("pvault_panel")){ die("Not Found");}
$dbhost = getenv('DB_HOST'); //MySQL Hostname
$dbuser = getenv('DB_USER'); //MySQL Username
$dbpass = getenv('DB_PASS'); //MySQL Password
$dbname = getenv('DB_NAME'); //MySQL DB name


$uploads_path = getenv('UPLOADS_PATH') ?: "uploads/";
$tmp_path = getenv('TMP_PATH') ?: "/tmp/";
$allowed_ext = getenv('FILE_EXT') ?: "pdf, doc, docx, xls, csv, xlsx, png, jpg, jpeg, gif";
$max_filesize = getenv('MAX_FILE_SIZE') ?: "4194304";

?>