<?php
//AUTO GENERATED BY INSTALLATION WIZARD
if (!defined("pvault_panel")){ die("Not Found");}
$dbhost = "localhost"; //MySQL Hostname
$dbuser = "pvault"; //MySQL Username
$dbpass = "pvault"; //MySQL Password
$dbname = "pvault"; //MySQL DB name


$uploads_path = "uploads/";
$tmp_path = "tmp/";
$allowed_ext = "pdf, doc, docx, xls, csv, xlsx, png, jpg, jpeg, gif";
$max_filesize = "4194304"; //in bytes
?>