<?php
//AUTO GENERATED BY INSTALLATION WIZARD
if (!defined("pvault_panel")){ die("Not Found");}
$dbhost = getenv('DB_HOST'); //MySQL Hostname
$dbuser = getenv('DB_USER'); //MySQL Username
$dbpass = getenv('DB_PASS'); //MySQL Password
$dbname = getenv('DB_NAME'); //MySQL DB name


$uploads_path = "uploads/";
$tmp_path = $uploads_path."tmp/";
$allowed_ext = "pdf, doc, docx, xls, csv, xlsx, png, jpg, jpeg, gif";
$max_filesize = "4194304"; //in bytes
?>